version: "2"

services:
  db:
    image: mysql
    env_file: .env
    restart: always
    volumes:
      - data-vanilla:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080

  app:
    image: suculent/vanilla-forum
    links:
     - db:mysql
    env_file: .env
    restart: always
    volumes:
     - ./uploads:/var/www/html/uploads
     - ./conf:/var/www/html/conf
    ports:
      - 8080:80

volumes:
  data-vanilla:
